### ISSUE TITLE
Where is the package "writeTableForEnrichmentMap.R"

### ISSUE THREAD

**Issue by koosle** [petrrysavy/circgpa-paper#1]
Dear author,
Hi!
Is there a package "writeTableForEnrichmentMap.R" in your source code? I couldn't find it.

**Comment by petrrysavy** [comment]
Hello,

Thank you very much for pointing this out, I forgot to upload the R file as I usually have to use a different shell script for cluster computations. Commit https://github.com/petrrysavy/circgpa-paper/commit/773a21f includes the file.
